### ISSUE TITLE
Unsafe numbers on start

### ISSUE THREAD

**Issue by DjovDev** [adamgibbons/ics#107]
Sometimes, I get the following error:

```
{ ValidationError: child "start" fails because ["start" at position 4 fails because ["4" must be a safe number]]
    at Object.exports.process (c:\NodeInvitation\node_modules\joi\lib\errors.js:203:19)
    at _validateWithOptions (c:\NodeInvitation\node_modules\joi\lib\types\any\index.js:764:31)
    at internals.root.root.validate (c:\NodeInvitation\node_modules\joi\lib\index.js:147:23)
    at validateEvent (c:\NodeInvitation\node_modules\ics\dist\schema\index.js:76:37)
    at validateAndBuildEvent (c:\NodeInvitation\node_modules\ics\dist\index.js:22:38)
    at Object.createEvent (c:\NodeInvitation\node_modules\ics\dist\index.js:102:32)
    at c:\NodeInvitation\Routes\fleetinvite.js:1580:37
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)
  isJoi: true,
  name: 'ValidationError',
  details: 
   [ { message: '"4" must be a safe number',
       path: [Object],
       type: 'number.unsafe',
       context: [Object] } ],
  _object: 
   { title: 'Tyre appointment',
     productId: 'adamgibbons/ics',
     method: 'PUBLISH',
     uid: 'd65705ff-2236-4321-8a48-76621f378ba0',
     timestamp: '20190404T114200Z',
     start: [ '2019', '04', '20', '08', '00' ],
     description: 'Test',
     startType: 'local',
     duration: { minutes: 60 } },
  annotate: [Function] }
```

I initialize an event with the following parameters:

```
{
title: 'Tyre appointment',
description: appfunctions.attemptToStringify(data[0].FIS_Description),
startType: 'local',
start: [appointmentMoment.format('YYYY'), appointmentMoment.format('MM'), appointmentMoment.format('DD'), appointmentMoment.format('HH'),appointmentMoment.format('mm')],
duration: { minutes: 60 }
}
```
I have solved this by adding parseInt() in front of every moment value.

I thought it was curious why the error is only thrown sometimes.

**Comment by adamgibbons** [comment]
@DjovDev `start` and `duration` expect numbers, not strings. They are validated using `Joi.number`: https://github.com/hapijs/joi/blob/v15.0.0/API.md#number---inherits-from-any
