### ISSUE TITLE
DIR or custom attributes not allowed within organizer/attendees

### ISSUE THREAD

**Issue by ibc** [adamgibbons/ics#86]
According to the spec, both `organizer` and `attendee` support [DIR](https://www.kanzaki.com/docs/ical/dir.html). Also, some calendar apps insert custom attributes (starting with `X-`).

However, **ics** fails when adding `dir` or any `x-xxxx` attribute. Example:

```js
const ics = require('ics')

const event =
{
	start       : [ 2018, 5, 30, 6, 30 ],
	duration    : { hours: 6, minutes: 30 },
	title       : 'Bolder Boulder',
	description : 'Annual 10-kilometer run in Boulder, Colorado',
	location    : 'Bilbao',
	url         : 'https://meet.sync.work/qwe/asd?qwe=1234',
	organizer   :
	{
		name   : 'Manolo Foo',
		email  : 'manolo@qweqwe.com',
		dir    : '1234-qwer-asdf',
		'x-id' : '1234-qwer-asdf'
	},
	attendees:
	[
		{
			name   : 'Adam Gibbons',
			email  : 'adam@example.com',
			dir    : '5678-rtty-dfgh',
			'x-id' : '5678-rtty-dfgh',
			rsvp   : true
		},
		{
			name   : 'Brittany Seaton',
			email  : 'brittany@example2.org',
			dir    : '9999-66666-tasd',
			'x-id' : '9999-66666-tasd'
		}
	]
};

ics.createEvent(event, (error, value) =>
{
	if (error)
	{
		console.error('ERROR:', error);

		return;
	}

	console.log(value);
});
```

It produces:

```
ERROR: { ValidationError: child "organizer" fails because ["dir" is not allowed, "x-id" is not allowed]
    at Object.exports.process (/private/tmp/node_modules/joi/lib/errors.js:181:19)
    at internals.Object._validateWithOptions (/private/tmp/node_modules/joi/lib/types/any/index.js:651:31)
    at module.exports.internals.Any.root.validate (/private/tmp/node_modules/joi/lib/index.js:121:23)
    at validateEvent (/private/tmp/node_modules/ics/dist/schema/index.js:72:37)
    at Object.createEvent (/private/tmp/node_modules/ics/dist/index.js:97:53)
    at Object.<anonymous> (/private/tmp/kk.js:36:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

**Comment by adamgibbons** [comment]
Closed by #87
